name: Version ğŸ·ï¸

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  version:
    name: Version ğŸ·ï¸
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read version tag ğŸ·ï¸
        id: get_version
        run: |
          input=$(grep version Software/wittypi/daemon.sh)
          [[ $input =~ ([0-9]+.[0-9]+) ]]
          echo version=${BASH_REMATCH[1]} >> $GITHUB_OUTPUT
      - name: Write version tag âœï¸
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.get_version.outputs.version }}
          force_push_tag: true
          message: ${{ github.event.head_commit.message }}
